# Generated by Django 3.2.3 on 2022-05-09 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Sheet',
            new_name='Shade',
        ),
        migrations.RenameModel(
            old_name='SheetData',
            new_name='ShadeData',
        ),
    ]
