# Generated by Django 3.2.3 on 2022-05-09 22:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0002_auto_20220509_2213'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shadedata',
            old_name='sheet',
            new_name='shade',
        ),
    ]
