# Generated by Django 3.2.3 on 2022-05-09 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysite', '0003_rename_sheet_shadedata_shade'),
    ]

    operations = [
        migrations.AddField(
            model_name='shade',
            name='colors',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='shade',
            name='max_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shade',
            name='max_width',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shade',
            name='min_height',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='shade',
            name='min_width',
            field=models.IntegerField(default=0),
        ),
    ]
